import org.apache.dubbo.config.spring.beans.factory.annotation.CompatibleReferenceAnnotationBeanPostProcessor;
public class FunctionUse7027 {
public void funcUse() {
CompatibleReferenceAnnotationBeanPostProcessor compatiblereferenceannotationbeanpostprocessor = new CompatibleReferenceAnnotationBeanPostProcessor();
compatiblereferenceannotationbeanpostprocessor.findMethodReferenceMetadata(null);
}
}